// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module design_1_v_frmbuf_wr_0_0_MultiPixStream2Bytes (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        StrmMPix_V_val_0_V_dout,
        StrmMPix_V_val_0_V_empty_n,
        StrmMPix_V_val_0_V_read,
        StrmMPix_V_val_1_V_dout,
        StrmMPix_V_val_1_V_empty_n,
        StrmMPix_V_val_1_V_read,
        StrmMPix_V_val_2_V_dout,
        StrmMPix_V_val_2_V_empty_n,
        StrmMPix_V_val_2_V_read,
        bytes_plane0_V_V_din,
        bytes_plane0_V_V_full_n,
        bytes_plane0_V_V_write,
        Height,
        WidthInPix,
        mul_ln135_loc_dout,
        mul_ln135_loc_empty_n,
        mul_ln135_loc_read,
        VideoFormat,
        mul_ln135_loc_out_din,
        mul_ln135_loc_out_full_n,
        mul_ln135_loc_out_write
);

parameter    ap_ST_fsm_state1 = 12'd1;
parameter    ap_ST_fsm_state2 = 12'd2;
parameter    ap_ST_fsm_state3 = 12'd4;
parameter    ap_ST_fsm_pp0_stage0 = 12'd8;
parameter    ap_ST_fsm_pp0_stage1 = 12'd16;
parameter    ap_ST_fsm_pp0_stage2 = 12'd32;
parameter    ap_ST_fsm_pp0_stage3 = 12'd64;
parameter    ap_ST_fsm_pp0_stage4 = 12'd128;
parameter    ap_ST_fsm_pp0_stage5 = 12'd256;
parameter    ap_ST_fsm_pp0_stage6 = 12'd512;
parameter    ap_ST_fsm_pp0_stage7 = 12'd1024;
parameter    ap_ST_fsm_state13 = 12'd2048;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [7:0] StrmMPix_V_val_0_V_dout;
input   StrmMPix_V_val_0_V_empty_n;
output   StrmMPix_V_val_0_V_read;
input  [7:0] StrmMPix_V_val_1_V_dout;
input   StrmMPix_V_val_1_V_empty_n;
output   StrmMPix_V_val_1_V_read;
input  [7:0] StrmMPix_V_val_2_V_dout;
input   StrmMPix_V_val_2_V_empty_n;
output   StrmMPix_V_val_2_V_read;
output  [63:0] bytes_plane0_V_V_din;
input   bytes_plane0_V_V_full_n;
output   bytes_plane0_V_V_write;
input  [15:0] Height;
input  [15:0] WidthInPix;
input  [15:0] mul_ln135_loc_dout;
input   mul_ln135_loc_empty_n;
output   mul_ln135_loc_read;
input  [7:0] VideoFormat;
output  [15:0] mul_ln135_loc_out_din;
input   mul_ln135_loc_out_full_n;
output   mul_ln135_loc_out_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg StrmMPix_V_val_0_V_read;
reg StrmMPix_V_val_1_V_read;
reg StrmMPix_V_val_2_V_read;
reg[63:0] bytes_plane0_V_V_din;
reg bytes_plane0_V_V_write;
reg mul_ln135_loc_read;
reg mul_ln135_loc_out_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [11:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    StrmMPix_V_val_0_V_blk_n;
wire    ap_CS_fsm_pp0_stage1;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage1;
reg   [0:0] icmp_ln622_reg_1379;
reg   [0:0] or_ln627_reg_1399;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2;
reg   [0:0] or_ln627_1_reg_1430;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3;
reg   [0:0] or_ln627_2_reg_1449;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_pp0_stage4;
reg   [0:0] or_ln627_3_reg_1468;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_pp0_stage5;
reg   [0:0] or_ln627_4_reg_1487;
wire    ap_CS_fsm_pp0_stage6;
wire    ap_block_pp0_stage6;
reg   [0:0] or_ln627_5_reg_1506;
wire    ap_CS_fsm_pp0_stage7;
wire    ap_block_pp0_stage7;
reg   [0:0] or_ln627_6_reg_1510;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] or_ln627_7_reg_1514;
reg    StrmMPix_V_val_1_V_blk_n;
reg    StrmMPix_V_val_2_V_blk_n;
reg    bytes_plane0_V_V_blk_n;
reg   [0:0] or_ln639_reg_1403;
reg   [0:0] or_ln639_1_reg_1407;
reg   [0:0] or_ln639_2_reg_1411;
reg    mul_ln135_loc_blk_n;
reg    mul_ln135_loc_out_blk_n;
reg   [11:0] x_0_i_i_reg_314;
reg   [7:0] pix_val_V_2_2_i_i_reg_325;
reg   [7:0] pix_val_V_1_2_i_i_reg_335;
reg   [7:0] pix_val_V_0_2_i_i_reg_345;
reg   [7:0] pix_val_V_2_3_i_i_reg_355;
reg   [7:0] pix_val_V_1_3_i_i_reg_366;
reg   [7:0] pix_val_V_0_3_i_i_reg_377;
reg   [7:0] pix_val_V_2_4_i_i_reg_388;
reg   [7:0] pix_val_V_2_5_i_i_reg_421;
reg   [7:0] pix_val_V_1_5_i_i_reg_432;
reg   [7:0] pix_val_V_0_5_i_i_reg_443;
reg   [7:0] pix_val_V_2_6_i_i_reg_454;
reg   [7:0] pix_val_V_1_6_i_i_reg_465;
reg   [7:0] pix_val_V_0_6_i_i_reg_476;
reg   [7:0] pix_val_V_2_7_i_i_reg_487;
reg   [7:0] pix_val_V_1_7_i_i_reg_498;
reg    ap_block_state1;
wire   [0:0] icmp_ln260_fu_611_p2;
reg   [0:0] icmp_ln260_reg_1213;
wire   [0:0] icmp_ln296_fu_617_p2;
reg   [0:0] icmp_ln296_reg_1217;
wire   [0:0] icmp_ln331_fu_639_p2;
reg   [0:0] icmp_ln331_reg_1221;
wire   [0:0] icmp_ln367_fu_645_p2;
reg   [0:0] icmp_ln367_reg_1225;
wire   [0:0] icmp_ln403_fu_651_p2;
reg   [0:0] icmp_ln403_reg_1229;
wire   [0:0] icmp_ln437_fu_673_p2;
reg   [0:0] icmp_ln437_reg_1233;
wire   [0:0] icmp_ln476_fu_695_p2;
reg   [0:0] icmp_ln476_reg_1237;
wire   [0:0] icmp_ln522_fu_717_p2;
reg   [0:0] icmp_ln522_reg_1241;
wire   [0:0] icmp_ln567_fu_739_p2;
reg   [0:0] icmp_ln567_reg_1245;
wire   [0:0] icmp_ln604_fu_761_p2;
reg   [0:0] icmp_ln604_reg_1249;
reg   [13:0] trunc_ln_reg_1277;
wire   [2:0] remPix_fu_787_p1;
wire   [12:0] trunc_ln1_fu_805_p4;
reg   [12:0] trunc_ln1_reg_1290;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln612_fu_817_p2;
wire   [12:0] add_ln627_fu_882_p2;
reg   [12:0] add_ln627_reg_1300;
wire   [0:0] icmp_ln627_fu_888_p2;
wire   [0:0] icmp_ln627_1_fu_904_p2;
wire   [0:0] icmp_ln627_2_fu_910_p2;
wire   [0:0] icmp_ln627_3_fu_926_p2;
wire   [0:0] icmp_ln627_4_fu_932_p2;
wire   [0:0] icmp_ln627_5_fu_938_p2;
wire   [0:0] icmp_ln627_6_fu_944_p2;
wire   [0:0] icmp_ln639_fu_950_p2;
wire   [0:0] icmp_ln639_1_fu_966_p2;
wire   [0:0] icmp_ln639_2_fu_972_p2;
wire   [0:0] icmp_ln618_fu_978_p2;
wire    ap_CS_fsm_state3;
wire   [15:0] y_fu_983_p2;
reg   [15:0] y_reg_1359;
wire    ap_block_state4_pp0_stage0_iter0;
wire    io_acc_block_signal_op214;
reg    ap_predicate_op214_read_state12;
reg    ap_block_state12_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln622_fu_1002_p2;
wire   [11:0] x_fu_1007_p2;
reg   [11:0] x_reg_1383;
wire   [0:0] icmp_ln627_7_fu_1013_p2;
reg   [0:0] icmp_ln627_7_reg_1388;
wire   [0:0] or_ln627_fu_1018_p2;
wire   [0:0] or_ln639_fu_1023_p2;
wire   [0:0] or_ln639_1_fu_1028_p2;
wire   [0:0] or_ln639_2_fu_1033_p2;
wire    io_acc_block_signal_op138;
reg    ap_predicate_op138_read_state5;
reg    ap_block_state5_pp0_stage1_iter0;
reg    ap_block_pp0_stage1_11001;
wire   [0:0] or_ln627_1_fu_1038_p2;
wire    io_acc_block_signal_op148;
reg    ap_predicate_op148_read_state6;
reg    ap_block_state6_pp0_stage2_iter0;
reg    ap_block_pp0_stage2_11001;
wire   [0:0] or_ln627_2_fu_1042_p2;
wire    io_acc_block_signal_op158;
reg    ap_predicate_op158_read_state7;
reg    ap_block_state7_pp0_stage3_iter0;
reg    ap_block_pp0_stage3_11001;
wire   [0:0] or_ln627_3_fu_1046_p2;
wire    io_acc_block_signal_op168;
reg    ap_predicate_op168_read_state8;
reg    ap_predicate_op175_write_state8;
reg    ap_block_state8_pp0_stage4_iter0;
reg    ap_block_pp0_stage4_11001;
wire   [0:0] or_ln627_4_fu_1050_p2;
wire    io_acc_block_signal_op181;
reg    ap_predicate_op181_read_state9;
reg    ap_block_state9_pp0_stage5_iter0;
reg    ap_block_pp0_stage5_11001;
wire   [0:0] or_ln627_5_fu_1075_p2;
wire   [0:0] or_ln627_6_fu_1079_p2;
wire   [0:0] or_ln627_7_fu_1083_p2;
wire    io_acc_block_signal_op193;
reg    ap_predicate_op193_read_state10;
reg    ap_block_state10_pp0_stage6_iter0;
reg    ap_block_pp0_stage6_11001;
wire    io_acc_block_signal_op202;
reg    ap_predicate_op202_read_state11;
reg    ap_predicate_op208_write_state11;
reg    ap_block_state11_pp0_stage7_iter0;
reg    ap_block_pp0_stage7_11001;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state4;
reg    ap_block_pp0_stage7_subdone;
reg   [15:0] y_0_i_i_reg_303;
wire    ap_CS_fsm_state13;
reg   [11:0] ap_phi_mux_x_0_i_i_phi_fu_318_p4;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_2_2_i_i_reg_325;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_1_2_i_i_reg_335;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_0_2_i_i_reg_345;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_2_3_i_i_reg_355;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_1_3_i_i_reg_366;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_0_3_i_i_reg_377;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_2_4_i_i_reg_388;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_1_4_i_i_reg_399;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_0_4_i_i_reg_410;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_2_5_i_i_reg_421;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_1_5_i_i_reg_432;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_0_5_i_i_reg_443;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_2_6_i_i_reg_454;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_1_6_i_i_reg_465;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_0_6_i_i_reg_476;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_2_7_i_i_reg_487;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_1_7_i_i_reg_498;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_0_7_i_i_reg_509;
wire   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_2_8_i_i_reg_520;
reg   [7:0] ap_phi_reg_pp0_iter1_pix_val_V_2_8_i_i_reg_520;
wire   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_1_8_i_i_reg_530;
reg   [7:0] ap_phi_reg_pp0_iter1_pix_val_V_1_8_i_i_reg_530;
wire   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_0_8_i_i_reg_540;
reg   [7:0] ap_phi_reg_pp0_iter1_pix_val_V_0_8_i_i_reg_540;
reg   [7:0] ap_phi_mux_pix_val_V_2_9_i_i_phi_fu_553_p4;
wire   [7:0] ap_phi_reg_pp0_iter1_pix_val_V_2_9_i_i_reg_550;
reg   [7:0] ap_phi_mux_pix_val_V_1_9_i_i_phi_fu_563_p4;
wire   [7:0] ap_phi_reg_pp0_iter1_pix_val_V_1_9_i_i_reg_560;
reg   [7:0] ap_phi_mux_pix_val_V_0_9_i_i_phi_fu_573_p4;
wire   [7:0] ap_phi_reg_pp0_iter1_pix_val_V_0_9_i_i_reg_570;
reg   [7:0] tmp_val_0_V_fu_242;
reg   [7:0] ap_sig_allocacmp_tmp_val_0_V_load;
reg   [7:0] tmp_val_1_V_fu_246;
reg   [7:0] ap_sig_allocacmp_tmp_val_1_V_load;
reg   [7:0] tmp_val_2_V_fu_250;
reg   [7:0] ap_sig_allocacmp_tmp_val_2_V_load;
wire   [63:0] tmp_V_fu_1054_p9;
reg    ap_block_pp0_stage4_01001;
wire   [63:0] tmp_V_1_fu_1087_p9;
reg    ap_block_pp0_stage7_01001;
wire   [63:0] tmp_V_2_fu_1160_p9;
reg    ap_block_pp0_stage0_01001;
wire   [7:0] add_ln260_fu_595_p2;
wire   [6:0] tmp_fu_601_p4;
wire   [7:0] add_ln331_fu_623_p2;
wire   [6:0] tmp_1_fu_629_p4;
wire   [7:0] add_ln437_fu_657_p2;
wire   [6:0] tmp_2_fu_663_p4;
wire   [7:0] add_ln476_fu_679_p2;
wire   [6:0] tmp_3_fu_685_p4;
wire   [7:0] add_ln522_fu_701_p2;
wire   [6:0] tmp_4_fu_707_p4;
wire   [7:0] add_ln567_fu_723_p2;
wire   [6:0] tmp_5_fu_729_p4;
wire   [7:0] add_ln604_fu_745_p2;
wire   [6:0] tmp_6_fu_751_p4;
wire   [16:0] zext_ln608_fu_767_p1;
wire   [16:0] add_ln608_fu_771_p2;
wire   [13:0] add_ln609_fu_796_p2;
wire   [29:0] mul_ln609_fu_1201_p2;
wire   [3:0] zext_ln611_fu_814_p1;
wire   [7:0] shl_ln_fu_830_p3;
wire   [5:0] shl_ln613_1_fu_841_p3;
wire   [8:0] zext_ln613_fu_837_p1;
wire   [8:0] zext_ln613_1_fu_848_p1;
wire   [8:0] sub_ln613_fu_852_p2;
wire   [8:0] add_ln613_fu_858_p2;
wire   [2:0] trunc_ln2_fu_864_p4;
wire   [3:0] remPix_2_fu_822_p3;
wire   [2:0] tmp_7_fu_894_p4;
wire   [1:0] tmp_8_fu_916_p4;
wire   [2:0] remainTrx_fu_874_p3;
wire   [1:0] tmp_9_fu_956_p4;
wire   [12:0] zext_ln622_fu_998_p1;
wire   [15:0] mul_ln609_fu_1201_p0;
wire   [13:0] mul_ln609_fu_1201_p1;
reg   [11:0] ap_NS_fsm;
reg    ap_block_pp0_stage1_subdone;
reg    ap_block_pp0_stage2_subdone;
reg    ap_block_pp0_stage3_subdone;
reg    ap_block_pp0_stage4_subdone;
reg    ap_block_pp0_stage5_subdone;
reg    ap_block_pp0_stage6_subdone;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [29:0] mul_ln609_fu_1201_p10;
reg    ap_condition_1221;
reg    ap_condition_1224;
reg    ap_condition_1229;
reg    ap_condition_1233;
reg    ap_condition_1237;
reg    ap_condition_1241;
reg    ap_condition_1245;
reg    ap_condition_548;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 12'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

design_1_v_frmbuf_wr_0_0_v_frmbuf_wr_mul_meOg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 30 ))
v_frmbuf_wr_mul_meOg_U27(
    .din0(mul_ln609_fu_1201_p0),
    .din1(mul_ln609_fu_1201_p1),
    .dout(mul_ln609_fu_1201_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state3) & ((icmp_ln260_reg_1213 == 1'd1) | ((icmp_ln296_reg_1217 == 1'd1) | ((icmp_ln331_reg_1221 == 1'd1) | ((icmp_ln367_reg_1225 == 1'd1) | ((icmp_ln403_reg_1229 == 1'd1) | ((icmp_ln437_reg_1233 == 1'd1) | ((icmp_ln476_reg_1237 == 1'd1) | ((icmp_ln522_reg_1241 == 1'd1) | ((icmp_ln567_reg_1245 == 1'd1) | ((icmp_ln618_fu_978_p2 == 1'd1) | (icmp_ln604_reg_1249 == 1'd0))))))))))))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state4) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((icmp_ln604_reg_1249 == 1'd1) & (icmp_ln618_fu_978_p2 == 1'd0) & (icmp_ln567_reg_1245 == 1'd0) & (icmp_ln522_reg_1241 == 1'd0) & (icmp_ln476_reg_1237 == 1'd0) & (icmp_ln437_reg_1233 == 1'd0) & (icmp_ln403_reg_1229 == 1'd0) & (icmp_ln367_reg_1225 == 1'd0) & (icmp_ln331_reg_1221 == 1'd0) & (icmp_ln296_reg_1217 == 1'd0) & (icmp_ln260_reg_1213 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage7_subdone) & (1'b1 == ap_CS_fsm_pp0_stage7)))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((icmp_ln604_reg_1249 == 1'd1) & (icmp_ln618_fu_978_p2 == 1'd0) & (icmp_ln567_reg_1245 == 1'd0) & (icmp_ln522_reg_1241 == 1'd0) & (icmp_ln476_reg_1237 == 1'd0) & (icmp_ln437_reg_1233 == 1'd0) & (icmp_ln403_reg_1229 == 1'd0) & (icmp_ln367_reg_1225 == 1'd0) & (icmp_ln331_reg_1221 == 1'd0) & (icmp_ln296_reg_1217 == 1'd0) & (icmp_ln260_reg_1213 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if ((1'b1 == ap_condition_1224)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_0_2_i_i_reg_345 <= ap_sig_allocacmp_tmp_val_0_V_load;
        end else if ((1'b1 == ap_condition_1221)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_0_2_i_i_reg_345 <= StrmMPix_V_val_0_V_dout;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1229)) begin
        if ((or_ln627_1_reg_1430 == 1'd0)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_0_3_i_i_reg_377 <= ap_phi_reg_pp0_iter0_pix_val_V_0_2_i_i_reg_345;
        end else if ((or_ln627_1_reg_1430 == 1'd1)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_0_3_i_i_reg_377 <= StrmMPix_V_val_0_V_dout;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1233)) begin
        if ((or_ln627_2_reg_1449 == 1'd0)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_0_4_i_i_reg_410 <= ap_phi_reg_pp0_iter0_pix_val_V_0_3_i_i_reg_377;
        end else if ((or_ln627_2_reg_1449 == 1'd1)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_0_4_i_i_reg_410 <= StrmMPix_V_val_0_V_dout;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1237)) begin
        if ((or_ln627_3_reg_1468 == 1'd0)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_0_5_i_i_reg_443 <= ap_phi_reg_pp0_iter0_pix_val_V_0_4_i_i_reg_410;
        end else if ((or_ln627_3_reg_1468 == 1'd1)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_0_5_i_i_reg_443 <= StrmMPix_V_val_0_V_dout;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1241)) begin
        if ((or_ln627_4_reg_1487 == 1'd0)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_0_6_i_i_reg_476 <= ap_phi_reg_pp0_iter0_pix_val_V_0_5_i_i_reg_443;
        end else if ((or_ln627_4_reg_1487 == 1'd1)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_0_6_i_i_reg_476 <= StrmMPix_V_val_0_V_dout;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1245)) begin
        if ((or_ln627_5_reg_1506 == 1'd0)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_0_7_i_i_reg_509 <= ap_phi_reg_pp0_iter0_pix_val_V_0_6_i_i_reg_476;
        end else if ((or_ln627_5_reg_1506 == 1'd1)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_0_7_i_i_reg_509 <= StrmMPix_V_val_0_V_dout;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if ((1'b1 == ap_condition_1224)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_1_2_i_i_reg_335 <= ap_sig_allocacmp_tmp_val_1_V_load;
        end else if ((1'b1 == ap_condition_1221)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_1_2_i_i_reg_335 <= StrmMPix_V_val_1_V_dout;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1229)) begin
        if ((or_ln627_1_reg_1430 == 1'd0)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_1_3_i_i_reg_366 <= ap_phi_reg_pp0_iter0_pix_val_V_1_2_i_i_reg_335;
        end else if ((or_ln627_1_reg_1430 == 1'd1)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_1_3_i_i_reg_366 <= StrmMPix_V_val_1_V_dout;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1233)) begin
        if ((or_ln627_2_reg_1449 == 1'd0)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_1_4_i_i_reg_399 <= ap_phi_reg_pp0_iter0_pix_val_V_1_3_i_i_reg_366;
        end else if ((or_ln627_2_reg_1449 == 1'd1)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_1_4_i_i_reg_399 <= StrmMPix_V_val_1_V_dout;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1237)) begin
        if ((or_ln627_3_reg_1468 == 1'd0)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_1_5_i_i_reg_432 <= ap_phi_reg_pp0_iter0_pix_val_V_1_4_i_i_reg_399;
        end else if ((or_ln627_3_reg_1468 == 1'd1)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_1_5_i_i_reg_432 <= StrmMPix_V_val_1_V_dout;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1241)) begin
        if ((or_ln627_4_reg_1487 == 1'd0)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_1_6_i_i_reg_465 <= ap_phi_reg_pp0_iter0_pix_val_V_1_5_i_i_reg_432;
        end else if ((or_ln627_4_reg_1487 == 1'd1)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_1_6_i_i_reg_465 <= StrmMPix_V_val_1_V_dout;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1245)) begin
        if ((or_ln627_5_reg_1506 == 1'd0)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_1_7_i_i_reg_498 <= ap_phi_reg_pp0_iter0_pix_val_V_1_6_i_i_reg_465;
        end else if ((or_ln627_5_reg_1506 == 1'd1)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_1_7_i_i_reg_498 <= StrmMPix_V_val_1_V_dout;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if ((1'b1 == ap_condition_1224)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_2_2_i_i_reg_325 <= ap_sig_allocacmp_tmp_val_2_V_load;
        end else if ((1'b1 == ap_condition_1221)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_2_2_i_i_reg_325 <= StrmMPix_V_val_2_V_dout;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1229)) begin
        if ((or_ln627_1_reg_1430 == 1'd0)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_2_3_i_i_reg_355 <= ap_phi_reg_pp0_iter0_pix_val_V_2_2_i_i_reg_325;
        end else if ((or_ln627_1_reg_1430 == 1'd1)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_2_3_i_i_reg_355 <= StrmMPix_V_val_2_V_dout;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1233)) begin
        if ((or_ln627_2_reg_1449 == 1'd0)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_2_4_i_i_reg_388 <= ap_phi_reg_pp0_iter0_pix_val_V_2_3_i_i_reg_355;
        end else if ((or_ln627_2_reg_1449 == 1'd1)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_2_4_i_i_reg_388 <= StrmMPix_V_val_2_V_dout;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1237)) begin
        if ((or_ln627_3_reg_1468 == 1'd0)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_2_5_i_i_reg_421 <= ap_phi_reg_pp0_iter0_pix_val_V_2_4_i_i_reg_388;
        end else if ((or_ln627_3_reg_1468 == 1'd1)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_2_5_i_i_reg_421 <= StrmMPix_V_val_2_V_dout;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1241)) begin
        if ((or_ln627_4_reg_1487 == 1'd0)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_2_6_i_i_reg_454 <= ap_phi_reg_pp0_iter0_pix_val_V_2_5_i_i_reg_421;
        end else if ((or_ln627_4_reg_1487 == 1'd1)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_2_6_i_i_reg_454 <= StrmMPix_V_val_2_V_dout;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1245)) begin
        if ((or_ln627_5_reg_1506 == 1'd0)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_2_7_i_i_reg_487 <= ap_phi_reg_pp0_iter0_pix_val_V_2_6_i_i_reg_454;
        end else if ((or_ln627_5_reg_1506 == 1'd1)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_2_7_i_i_reg_487 <= StrmMPix_V_val_2_V_dout;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_548)) begin
        if (((icmp_ln622_reg_1379 == 1'd1) & (or_ln627_6_reg_1510 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_pix_val_V_0_8_i_i_reg_540 <= ap_phi_reg_pp0_iter0_pix_val_V_0_7_i_i_reg_509;
        end else if (((or_ln627_6_reg_1510 == 1'd1) & (icmp_ln622_reg_1379 == 1'd1))) begin
            ap_phi_reg_pp0_iter1_pix_val_V_0_8_i_i_reg_540 <= StrmMPix_V_val_0_V_dout;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_pix_val_V_0_8_i_i_reg_540 <= ap_phi_reg_pp0_iter0_pix_val_V_0_8_i_i_reg_540;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_548)) begin
        if (((icmp_ln622_reg_1379 == 1'd1) & (or_ln627_6_reg_1510 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_pix_val_V_1_8_i_i_reg_530 <= ap_phi_reg_pp0_iter0_pix_val_V_1_7_i_i_reg_498;
        end else if (((or_ln627_6_reg_1510 == 1'd1) & (icmp_ln622_reg_1379 == 1'd1))) begin
            ap_phi_reg_pp0_iter1_pix_val_V_1_8_i_i_reg_530 <= StrmMPix_V_val_1_V_dout;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_pix_val_V_1_8_i_i_reg_530 <= ap_phi_reg_pp0_iter0_pix_val_V_1_8_i_i_reg_530;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_548)) begin
        if (((icmp_ln622_reg_1379 == 1'd1) & (or_ln627_6_reg_1510 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_pix_val_V_2_8_i_i_reg_520 <= ap_phi_reg_pp0_iter0_pix_val_V_2_7_i_i_reg_487;
        end else if (((or_ln627_6_reg_1510 == 1'd1) & (icmp_ln622_reg_1379 == 1'd1))) begin
            ap_phi_reg_pp0_iter1_pix_val_V_2_8_i_i_reg_520 <= StrmMPix_V_val_2_V_dout;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_pix_val_V_2_8_i_i_reg_520 <= ap_phi_reg_pp0_iter0_pix_val_V_2_8_i_i_reg_520;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln622_reg_1379 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_0_i_i_reg_314 <= x_reg_1383;
    end else if (((icmp_ln604_reg_1249 == 1'd1) & (icmp_ln618_fu_978_p2 == 1'd0) & (icmp_ln567_reg_1245 == 1'd0) & (icmp_ln522_reg_1241 == 1'd0) & (icmp_ln476_reg_1237 == 1'd0) & (icmp_ln437_reg_1233 == 1'd0) & (icmp_ln403_reg_1229 == 1'd0) & (icmp_ln367_reg_1225 == 1'd0) & (icmp_ln331_reg_1221 == 1'd0) & (icmp_ln296_reg_1217 == 1'd0) & (icmp_ln260_reg_1213 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        x_0_i_i_reg_314 <= 12'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        y_0_i_i_reg_303 <= y_reg_1359;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        y_0_i_i_reg_303 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln627_reg_1300 <= add_ln627_fu_882_p2;
        trunc_ln1_reg_1290 <= {{mul_ln609_fu_1201_p2[28:16]}};
    end
end

always @ (posedge ap_clk) begin
    if ((~((mul_ln135_loc_out_full_n == 1'b0) | (mul_ln135_loc_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        icmp_ln260_reg_1213 <= icmp_ln260_fu_611_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((mul_ln135_loc_out_full_n == 1'b0) | (mul_ln135_loc_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (icmp_ln260_fu_611_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        icmp_ln296_reg_1217 <= icmp_ln296_fu_617_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((mul_ln135_loc_out_full_n == 1'b0) | (mul_ln135_loc_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (icmp_ln296_fu_617_p2 == 1'd0) & (icmp_ln260_fu_611_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        icmp_ln331_reg_1221 <= icmp_ln331_fu_639_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((mul_ln135_loc_out_full_n == 1'b0) | (mul_ln135_loc_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (icmp_ln331_fu_639_p2 == 1'd0) & (icmp_ln296_fu_617_p2 == 1'd0) & (icmp_ln260_fu_611_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        icmp_ln367_reg_1225 <= icmp_ln367_fu_645_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((mul_ln135_loc_out_full_n == 1'b0) | (mul_ln135_loc_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (icmp_ln367_fu_645_p2 == 1'd0) & (icmp_ln331_fu_639_p2 == 1'd0) & (icmp_ln296_fu_617_p2 == 1'd0) & (icmp_ln260_fu_611_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        icmp_ln403_reg_1229 <= icmp_ln403_fu_651_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((mul_ln135_loc_out_full_n == 1'b0) | (mul_ln135_loc_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (icmp_ln403_fu_651_p2 == 1'd0) & (icmp_ln367_fu_645_p2 == 1'd0) & (icmp_ln331_fu_639_p2 == 1'd0) & (icmp_ln296_fu_617_p2 == 1'd0) & (icmp_ln260_fu_611_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        icmp_ln437_reg_1233 <= icmp_ln437_fu_673_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((mul_ln135_loc_out_full_n == 1'b0) | (mul_ln135_loc_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (icmp_ln437_fu_673_p2 == 1'd0) & (icmp_ln403_fu_651_p2 == 1'd0) & (icmp_ln367_fu_645_p2 == 1'd0) & (icmp_ln331_fu_639_p2 == 1'd0) & (icmp_ln296_fu_617_p2 == 1'd0) & (icmp_ln260_fu_611_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        icmp_ln476_reg_1237 <= icmp_ln476_fu_695_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((mul_ln135_loc_out_full_n == 1'b0) | (mul_ln135_loc_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (icmp_ln476_fu_695_p2 == 1'd0) & (icmp_ln437_fu_673_p2 == 1'd0) & (icmp_ln403_fu_651_p2 == 1'd0) & (icmp_ln367_fu_645_p2 == 1'd0) & (icmp_ln331_fu_639_p2 == 1'd0) & (icmp_ln296_fu_617_p2 == 1'd0) & (icmp_ln260_fu_611_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        icmp_ln522_reg_1241 <= icmp_ln522_fu_717_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((mul_ln135_loc_out_full_n == 1'b0) | (mul_ln135_loc_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (icmp_ln522_fu_717_p2 == 1'd0) & (icmp_ln476_fu_695_p2 == 1'd0) & (icmp_ln437_fu_673_p2 == 1'd0) & (icmp_ln403_fu_651_p2 == 1'd0) & (icmp_ln367_fu_645_p2 == 1'd0) & (icmp_ln331_fu_639_p2 == 1'd0) & (icmp_ln296_fu_617_p2 == 1'd0) & (icmp_ln260_fu_611_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        icmp_ln567_reg_1245 <= icmp_ln567_fu_739_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((mul_ln135_loc_out_full_n == 1'b0) | (mul_ln135_loc_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (icmp_ln567_fu_739_p2 == 1'd0) & (icmp_ln522_fu_717_p2 == 1'd0) & (icmp_ln476_fu_695_p2 == 1'd0) & (icmp_ln437_fu_673_p2 == 1'd0) & (icmp_ln403_fu_651_p2 == 1'd0) & (icmp_ln367_fu_645_p2 == 1'd0) & (icmp_ln331_fu_639_p2 == 1'd0) & (icmp_ln296_fu_617_p2 == 1'd0) & (icmp_ln260_fu_611_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        icmp_ln604_reg_1249 <= icmp_ln604_fu_761_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln622_reg_1379 <= icmp_ln622_fu_1002_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln622_fu_1002_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln627_7_reg_1388 <= icmp_ln627_7_fu_1013_p2;
        or_ln627_reg_1399 <= or_ln627_fu_1018_p2;
        or_ln639_1_reg_1407 <= or_ln639_1_fu_1028_p2;
        or_ln639_2_reg_1411 <= or_ln639_2_fu_1033_p2;
        or_ln639_reg_1403 <= or_ln639_fu_1023_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln622_reg_1379 == 1'd1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        or_ln627_1_reg_1430 <= or_ln627_1_fu_1038_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln622_reg_1379 == 1'd1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        or_ln627_2_reg_1449 <= or_ln627_2_fu_1042_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln622_reg_1379 == 1'd1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        or_ln627_3_reg_1468 <= or_ln627_3_fu_1046_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln622_reg_1379 == 1'd1) & (1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        or_ln627_4_reg_1487 <= or_ln627_4_fu_1050_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln622_reg_1379 == 1'd1) & (1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        or_ln627_5_reg_1506 <= or_ln627_5_fu_1075_p2;
        or_ln627_6_reg_1510 <= or_ln627_6_fu_1079_p2;
        or_ln627_7_reg_1514 <= or_ln627_7_fu_1083_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        pix_val_V_0_2_i_i_reg_345 <= ap_phi_reg_pp0_iter0_pix_val_V_0_2_i_i_reg_345;
        pix_val_V_1_2_i_i_reg_335 <= ap_phi_reg_pp0_iter0_pix_val_V_1_2_i_i_reg_335;
        pix_val_V_2_2_i_i_reg_325 <= ap_phi_reg_pp0_iter0_pix_val_V_2_2_i_i_reg_325;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        pix_val_V_0_3_i_i_reg_377 <= ap_phi_reg_pp0_iter0_pix_val_V_0_3_i_i_reg_377;
        pix_val_V_1_3_i_i_reg_366 <= ap_phi_reg_pp0_iter0_pix_val_V_1_3_i_i_reg_366;
        pix_val_V_2_3_i_i_reg_355 <= ap_phi_reg_pp0_iter0_pix_val_V_2_3_i_i_reg_355;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        pix_val_V_0_5_i_i_reg_443 <= ap_phi_reg_pp0_iter0_pix_val_V_0_5_i_i_reg_443;
        pix_val_V_1_5_i_i_reg_432 <= ap_phi_reg_pp0_iter0_pix_val_V_1_5_i_i_reg_432;
        pix_val_V_2_5_i_i_reg_421 <= ap_phi_reg_pp0_iter0_pix_val_V_2_5_i_i_reg_421;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        pix_val_V_0_6_i_i_reg_476 <= ap_phi_reg_pp0_iter0_pix_val_V_0_6_i_i_reg_476;
        pix_val_V_1_6_i_i_reg_465 <= ap_phi_reg_pp0_iter0_pix_val_V_1_6_i_i_reg_465;
        pix_val_V_2_6_i_i_reg_454 <= ap_phi_reg_pp0_iter0_pix_val_V_2_6_i_i_reg_454;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        pix_val_V_1_7_i_i_reg_498 <= ap_phi_reg_pp0_iter0_pix_val_V_1_7_i_i_reg_498;
        pix_val_V_2_7_i_i_reg_487 <= ap_phi_reg_pp0_iter0_pix_val_V_2_7_i_i_reg_487;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        pix_val_V_2_4_i_i_reg_388 <= ap_phi_reg_pp0_iter0_pix_val_V_2_4_i_i_reg_388;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln622_reg_1379 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_val_0_V_fu_242 <= ap_phi_mux_pix_val_V_0_9_i_i_phi_fu_573_p4;
        tmp_val_1_V_fu_246 <= ap_phi_mux_pix_val_V_1_9_i_i_phi_fu_563_p4;
        tmp_val_2_V_fu_250 <= ap_phi_mux_pix_val_V_2_9_i_i_phi_fu_553_p4;
    end
end

always @ (posedge ap_clk) begin
    if ((~((mul_ln135_loc_out_full_n == 1'b0) | (mul_ln135_loc_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (icmp_ln604_fu_761_p2 == 1'd1) & (icmp_ln567_fu_739_p2 == 1'd0) & (icmp_ln522_fu_717_p2 == 1'd0) & (icmp_ln476_fu_695_p2 == 1'd0) & (icmp_ln437_fu_673_p2 == 1'd0) & (icmp_ln403_fu_651_p2 == 1'd0) & (icmp_ln367_fu_645_p2 == 1'd0) & (icmp_ln331_fu_639_p2 == 1'd0) & (icmp_ln296_fu_617_p2 == 1'd0) & (icmp_ln260_fu_611_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        trunc_ln_reg_1277 <= {{add_ln608_fu_771_p2[16:3]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_reg_1383 <= x_fu_1007_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln604_reg_1249 == 1'd1) & (icmp_ln567_reg_1245 == 1'd0) & (icmp_ln522_reg_1241 == 1'd0) & (icmp_ln476_reg_1237 == 1'd0) & (icmp_ln437_reg_1233 == 1'd0) & (icmp_ln403_reg_1229 == 1'd0) & (icmp_ln367_reg_1225 == 1'd0) & (icmp_ln331_reg_1221 == 1'd0) & (icmp_ln296_reg_1217 == 1'd0) & (icmp_ln260_reg_1213 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        y_reg_1359 <= y_fu_983_p2;
    end
end

always @ (*) begin
    if ((((or_ln627_7_reg_1514 == 1'd1) & (icmp_ln622_reg_1379 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage2) & (or_ln627_1_reg_1430 == 1'd1) & (icmp_ln622_reg_1379 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((or_ln627_6_reg_1510 == 1'd1) & (icmp_ln622_reg_1379 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7)) | ((or_ln627_5_reg_1506 == 1'd1) & (icmp_ln622_reg_1379 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6)) | ((or_ln627_4_reg_1487 == 1'd1) & (icmp_ln622_reg_1379 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5)) | ((or_ln627_3_reg_1468 == 1'd1) & (icmp_ln622_reg_1379 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4)) | ((or_ln627_2_reg_1449 == 1'd1) & (icmp_ln622_reg_1379 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3)) | ((or_ln627_reg_1399 == 1'd1) & (icmp_ln622_reg_1379 == 1'd1) & (1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        StrmMPix_V_val_0_V_blk_n = StrmMPix_V_val_0_V_empty_n;
    end else begin
        StrmMPix_V_val_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (ap_predicate_op148_read_state6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage7_11001) & (ap_predicate_op202_read_state11 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage6_11001) & (ap_predicate_op193_read_state10 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_predicate_op181_read_state9 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_predicate_op168_read_state8 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_predicate_op158_read_state7 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_predicate_op138_read_state5 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op214_read_state12 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        StrmMPix_V_val_0_V_read = 1'b1;
    end else begin
        StrmMPix_V_val_0_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((((or_ln627_7_reg_1514 == 1'd1) & (icmp_ln622_reg_1379 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage2) & (or_ln627_1_reg_1430 == 1'd1) & (icmp_ln622_reg_1379 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((or_ln627_6_reg_1510 == 1'd1) & (icmp_ln622_reg_1379 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7)) | ((or_ln627_5_reg_1506 == 1'd1) & (icmp_ln622_reg_1379 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6)) | ((or_ln627_4_reg_1487 == 1'd1) & (icmp_ln622_reg_1379 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5)) | ((or_ln627_3_reg_1468 == 1'd1) & (icmp_ln622_reg_1379 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4)) | ((or_ln627_2_reg_1449 == 1'd1) & (icmp_ln622_reg_1379 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3)) | ((or_ln627_reg_1399 == 1'd1) & (icmp_ln622_reg_1379 == 1'd1) & (1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        StrmMPix_V_val_1_V_blk_n = StrmMPix_V_val_1_V_empty_n;
    end else begin
        StrmMPix_V_val_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (ap_predicate_op148_read_state6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage7_11001) & (ap_predicate_op202_read_state11 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage6_11001) & (ap_predicate_op193_read_state10 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_predicate_op181_read_state9 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_predicate_op168_read_state8 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_predicate_op158_read_state7 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_predicate_op138_read_state5 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op214_read_state12 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        StrmMPix_V_val_1_V_read = 1'b1;
    end else begin
        StrmMPix_V_val_1_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((((or_ln627_7_reg_1514 == 1'd1) & (icmp_ln622_reg_1379 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage2) & (or_ln627_1_reg_1430 == 1'd1) & (icmp_ln622_reg_1379 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((or_ln627_6_reg_1510 == 1'd1) & (icmp_ln622_reg_1379 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7)) | ((or_ln627_5_reg_1506 == 1'd1) & (icmp_ln622_reg_1379 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6)) | ((or_ln627_4_reg_1487 == 1'd1) & (icmp_ln622_reg_1379 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5)) | ((or_ln627_3_reg_1468 == 1'd1) & (icmp_ln622_reg_1379 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4)) | ((or_ln627_2_reg_1449 == 1'd1) & (icmp_ln622_reg_1379 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3)) | ((or_ln627_reg_1399 == 1'd1) & (icmp_ln622_reg_1379 == 1'd1) & (1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        StrmMPix_V_val_2_V_blk_n = StrmMPix_V_val_2_V_empty_n;
    end else begin
        StrmMPix_V_val_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (ap_predicate_op148_read_state6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage7_11001) & (ap_predicate_op202_read_state11 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage6_11001) & (ap_predicate_op193_read_state10 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_predicate_op181_read_state9 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_predicate_op168_read_state8 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_predicate_op158_read_state7 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_predicate_op138_read_state5 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op214_read_state12 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        StrmMPix_V_val_2_V_read = 1'b1;
    end else begin
        StrmMPix_V_val_2_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln622_fu_1002_p2 == 1'd0)) begin
        ap_condition_pp0_exit_iter0_state4 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state4 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & ((icmp_ln260_reg_1213 == 1'd1) | ((icmp_ln296_reg_1217 == 1'd1) | ((icmp_ln331_reg_1221 == 1'd1) | ((icmp_ln367_reg_1225 == 1'd1) | ((icmp_ln403_reg_1229 == 1'd1) | ((icmp_ln437_reg_1233 == 1'd1) | ((icmp_ln476_reg_1237 == 1'd1) | ((icmp_ln522_reg_1241 == 1'd1) | ((icmp_ln567_reg_1245 == 1'd1) | ((icmp_ln618_fu_978_p2 == 1'd1) | (icmp_ln604_reg_1249 == 1'd0))))))))))))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln622_reg_1379 == 1'd1)) begin
        if ((or_ln627_7_reg_1514 == 1'd0)) begin
            ap_phi_mux_pix_val_V_0_9_i_i_phi_fu_573_p4 = ap_phi_reg_pp0_iter1_pix_val_V_0_8_i_i_reg_540;
        end else if ((or_ln627_7_reg_1514 == 1'd1)) begin
            ap_phi_mux_pix_val_V_0_9_i_i_phi_fu_573_p4 = StrmMPix_V_val_0_V_dout;
        end else begin
            ap_phi_mux_pix_val_V_0_9_i_i_phi_fu_573_p4 = ap_phi_reg_pp0_iter1_pix_val_V_0_9_i_i_reg_570;
        end
    end else begin
        ap_phi_mux_pix_val_V_0_9_i_i_phi_fu_573_p4 = ap_phi_reg_pp0_iter1_pix_val_V_0_9_i_i_reg_570;
    end
end

always @ (*) begin
    if ((icmp_ln622_reg_1379 == 1'd1)) begin
        if ((or_ln627_7_reg_1514 == 1'd0)) begin
            ap_phi_mux_pix_val_V_1_9_i_i_phi_fu_563_p4 = ap_phi_reg_pp0_iter1_pix_val_V_1_8_i_i_reg_530;
        end else if ((or_ln627_7_reg_1514 == 1'd1)) begin
            ap_phi_mux_pix_val_V_1_9_i_i_phi_fu_563_p4 = StrmMPix_V_val_1_V_dout;
        end else begin
            ap_phi_mux_pix_val_V_1_9_i_i_phi_fu_563_p4 = ap_phi_reg_pp0_iter1_pix_val_V_1_9_i_i_reg_560;
        end
    end else begin
        ap_phi_mux_pix_val_V_1_9_i_i_phi_fu_563_p4 = ap_phi_reg_pp0_iter1_pix_val_V_1_9_i_i_reg_560;
    end
end

always @ (*) begin
    if ((icmp_ln622_reg_1379 == 1'd1)) begin
        if ((or_ln627_7_reg_1514 == 1'd0)) begin
            ap_phi_mux_pix_val_V_2_9_i_i_phi_fu_553_p4 = ap_phi_reg_pp0_iter1_pix_val_V_2_8_i_i_reg_520;
        end else if ((or_ln627_7_reg_1514 == 1'd1)) begin
            ap_phi_mux_pix_val_V_2_9_i_i_phi_fu_553_p4 = StrmMPix_V_val_2_V_dout;
        end else begin
            ap_phi_mux_pix_val_V_2_9_i_i_phi_fu_553_p4 = ap_phi_reg_pp0_iter1_pix_val_V_2_9_i_i_reg_550;
        end
    end else begin
        ap_phi_mux_pix_val_V_2_9_i_i_phi_fu_553_p4 = ap_phi_reg_pp0_iter1_pix_val_V_2_9_i_i_reg_550;
    end
end

always @ (*) begin
    if (((icmp_ln622_reg_1379 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_x_0_i_i_phi_fu_318_p4 = x_reg_1383;
    end else begin
        ap_phi_mux_x_0_i_i_phi_fu_318_p4 = x_0_i_i_reg_314;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & ((icmp_ln260_reg_1213 == 1'd1) | ((icmp_ln296_reg_1217 == 1'd1) | ((icmp_ln331_reg_1221 == 1'd1) | ((icmp_ln367_reg_1225 == 1'd1) | ((icmp_ln403_reg_1229 == 1'd1) | ((icmp_ln437_reg_1233 == 1'd1) | ((icmp_ln476_reg_1237 == 1'd1) | ((icmp_ln522_reg_1241 == 1'd1) | ((icmp_ln567_reg_1245 == 1'd1) | ((icmp_ln618_fu_978_p2 == 1'd1) | (icmp_ln604_reg_1249 == 1'd0))))))))))))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln622_reg_1379 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_tmp_val_0_V_load = ap_phi_mux_pix_val_V_0_9_i_i_phi_fu_573_p4;
    end else begin
        ap_sig_allocacmp_tmp_val_0_V_load = tmp_val_0_V_fu_242;
    end
end

always @ (*) begin
    if (((icmp_ln622_reg_1379 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_tmp_val_1_V_load = ap_phi_mux_pix_val_V_1_9_i_i_phi_fu_563_p4;
    end else begin
        ap_sig_allocacmp_tmp_val_1_V_load = tmp_val_1_V_fu_246;
    end
end

always @ (*) begin
    if (((icmp_ln622_reg_1379 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_tmp_val_2_V_load = ap_phi_mux_pix_val_V_2_9_i_i_phi_fu_553_p4;
    end else begin
        ap_sig_allocacmp_tmp_val_2_V_load = tmp_val_2_V_fu_250;
    end
end

always @ (*) begin
    if ((((or_ln639_1_reg_1407 == 1'd1) & (icmp_ln622_reg_1379 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7)) | ((or_ln639_reg_1403 == 1'd1) & (icmp_ln622_reg_1379 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4)) | ((or_ln639_2_reg_1411 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0)))) begin
        bytes_plane0_V_V_blk_n = bytes_plane0_V_V_full_n;
    end else begin
        bytes_plane0_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((or_ln639_2_reg_1411 == 1'd1) & (1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bytes_plane0_V_V_din = tmp_V_2_fu_1160_p9;
    end else if (((1'b0 == ap_block_pp0_stage7_01001) & (ap_predicate_op208_write_state11 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        bytes_plane0_V_V_din = tmp_V_1_fu_1087_p9;
    end else if (((1'b0 == ap_block_pp0_stage4_01001) & (ap_predicate_op175_write_state8 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        bytes_plane0_V_V_din = tmp_V_fu_1054_p9;
    end else begin
        bytes_plane0_V_V_din = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage7_11001) & (ap_predicate_op208_write_state11 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_predicate_op175_write_state8 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((or_ln639_2_reg_1411 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        bytes_plane0_V_V_write = 1'b1;
    end else begin
        bytes_plane0_V_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        mul_ln135_loc_blk_n = mul_ln135_loc_empty_n;
    end else begin
        mul_ln135_loc_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        mul_ln135_loc_out_blk_n = mul_ln135_loc_out_full_n;
    end else begin
        mul_ln135_loc_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((mul_ln135_loc_out_full_n == 1'b0) | (mul_ln135_loc_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        mul_ln135_loc_out_write = 1'b1;
    end else begin
        mul_ln135_loc_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((mul_ln135_loc_out_full_n == 1'b0) | (mul_ln135_loc_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        mul_ln135_loc_read = 1'b1;
    end else begin
        mul_ln135_loc_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((mul_ln135_loc_out_full_n == 1'b0) | (mul_ln135_loc_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (icmp_ln604_fu_761_p2 == 1'd1) & (icmp_ln567_fu_739_p2 == 1'd0) & (icmp_ln522_fu_717_p2 == 1'd0) & (icmp_ln476_fu_695_p2 == 1'd0) & (icmp_ln437_fu_673_p2 == 1'd0) & (icmp_ln403_fu_651_p2 == 1'd0) & (icmp_ln367_fu_645_p2 == 1'd0) & (icmp_ln331_fu_639_p2 == 1'd0) & (icmp_ln296_fu_617_p2 == 1'd0) & (icmp_ln260_fu_611_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else if ((~((mul_ln135_loc_out_full_n == 1'b0) | (mul_ln135_loc_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1) & ((icmp_ln260_fu_611_p2 == 1'd1) | ((icmp_ln296_fu_617_p2 == 1'd1) | ((icmp_ln331_fu_639_p2 == 1'd1) | ((icmp_ln367_fu_645_p2 == 1'd1) | ((icmp_ln403_fu_651_p2 == 1'd1) | ((icmp_ln437_fu_673_p2 == 1'd1) | ((icmp_ln476_fu_695_p2 == 1'd1) | ((icmp_ln522_fu_717_p2 == 1'd1) | ((icmp_ln567_fu_739_p2 == 1'd1) | (icmp_ln604_fu_761_p2 == 1'd0)))))))))))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & ((icmp_ln260_reg_1213 == 1'd1) | ((icmp_ln296_reg_1217 == 1'd1) | ((icmp_ln331_reg_1221 == 1'd1) | ((icmp_ln367_reg_1225 == 1'd1) | ((icmp_ln403_reg_1229 == 1'd1) | ((icmp_ln437_reg_1233 == 1'd1) | ((icmp_ln476_reg_1237 == 1'd1) | ((icmp_ln522_reg_1241 == 1'd1) | ((icmp_ln567_reg_1245 == 1'd1) | ((icmp_ln618_fu_978_p2 == 1'd1) | (icmp_ln604_reg_1249 == 1'd0))))))))))))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln622_fu_1002_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln622_fu_1002_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_pp0_stage6 : begin
            if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end
        end
        ap_ST_fsm_pp0_stage7 : begin
            if ((1'b0 == ap_block_pp0_stage7_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln260_fu_595_p2 = ($signed(VideoFormat) + $signed(8'd246));

assign add_ln331_fu_623_p2 = ($signed(VideoFormat) + $signed(8'd241));

assign add_ln437_fu_657_p2 = ($signed(VideoFormat) + $signed(8'd238));

assign add_ln476_fu_679_p2 = ($signed(VideoFormat) + $signed(8'd234));

assign add_ln522_fu_701_p2 = ($signed(VideoFormat) + $signed(8'd224));

assign add_ln567_fu_723_p2 = ($signed(VideoFormat) + $signed(8'd219));

assign add_ln604_fu_745_p2 = ($signed(VideoFormat) + $signed(8'd236));

assign add_ln608_fu_771_p2 = (17'd7 + zext_ln608_fu_767_p1);

assign add_ln609_fu_796_p2 = (14'd2 + trunc_ln_reg_1277);

assign add_ln613_fu_858_p2 = (9'd63 + sub_ln613_fu_852_p2);

assign add_ln627_fu_882_p2 = ($signed(13'd8191) + $signed(trunc_ln1_fu_805_p4));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_pp0_stage6 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_pp0_stage7 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((io_acc_block_signal_op214 == 1'b0) & (ap_predicate_op214_read_state12 == 1'b1)) | ((or_ln639_2_reg_1411 == 1'd1) & (bytes_plane0_V_V_full_n == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((io_acc_block_signal_op214 == 1'b0) & (ap_predicate_op214_read_state12 == 1'b1)) | ((or_ln639_2_reg_1411 == 1'd1) & (bytes_plane0_V_V_full_n == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((io_acc_block_signal_op214 == 1'b0) & (ap_predicate_op214_read_state12 == 1'b1)) | ((or_ln639_2_reg_1411 == 1'd1) & (bytes_plane0_V_V_full_n == 1'b0))));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001 = ((io_acc_block_signal_op138 == 1'b0) & (ap_predicate_op138_read_state5 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = ((io_acc_block_signal_op138 == 1'b0) & (ap_predicate_op138_read_state5 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_11001 = ((io_acc_block_signal_op148 == 1'b0) & (ap_predicate_op148_read_state6 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage2_subdone = ((io_acc_block_signal_op148 == 1'b0) & (ap_predicate_op148_read_state6 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_11001 = ((io_acc_block_signal_op158 == 1'b0) & (ap_predicate_op158_read_state7 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage3_subdone = ((io_acc_block_signal_op158 == 1'b0) & (ap_predicate_op158_read_state7 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage4_01001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (((io_acc_block_signal_op168 == 1'b0) & (ap_predicate_op168_read_state8 == 1'b1)) | ((bytes_plane0_V_V_full_n == 1'b0) & (ap_predicate_op175_write_state8 == 1'b1))));
end

always @ (*) begin
    ap_block_pp0_stage4_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (((io_acc_block_signal_op168 == 1'b0) & (ap_predicate_op168_read_state8 == 1'b1)) | ((bytes_plane0_V_V_full_n == 1'b0) & (ap_predicate_op175_write_state8 == 1'b1))));
end

always @ (*) begin
    ap_block_pp0_stage4_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & (((io_acc_block_signal_op168 == 1'b0) & (ap_predicate_op168_read_state8 == 1'b1)) | ((bytes_plane0_V_V_full_n == 1'b0) & (ap_predicate_op175_write_state8 == 1'b1))));
end

assign ap_block_pp0_stage5 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage5_11001 = ((io_acc_block_signal_op181 == 1'b0) & (ap_predicate_op181_read_state9 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage5_subdone = ((io_acc_block_signal_op181 == 1'b0) & (ap_predicate_op181_read_state9 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

assign ap_block_pp0_stage6 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage6_11001 = ((io_acc_block_signal_op193 == 1'b0) & (ap_predicate_op193_read_state10 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage6_subdone = ((io_acc_block_signal_op193 == 1'b0) & (ap_predicate_op193_read_state10 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

assign ap_block_pp0_stage7 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage7_01001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (((io_acc_block_signal_op202 == 1'b0) & (ap_predicate_op202_read_state11 == 1'b1)) | ((bytes_plane0_V_V_full_n == 1'b0) & (ap_predicate_op208_write_state11 == 1'b1))));
end

always @ (*) begin
    ap_block_pp0_stage7_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (((io_acc_block_signal_op202 == 1'b0) & (ap_predicate_op202_read_state11 == 1'b1)) | ((bytes_plane0_V_V_full_n == 1'b0) & (ap_predicate_op208_write_state11 == 1'b1))));
end

always @ (*) begin
    ap_block_pp0_stage7_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & (((io_acc_block_signal_op202 == 1'b0) & (ap_predicate_op202_read_state11 == 1'b1)) | ((bytes_plane0_V_V_full_n == 1'b0) & (ap_predicate_op208_write_state11 == 1'b1))));
end

always @ (*) begin
    ap_block_state1 = ((mul_ln135_loc_out_full_n == 1'b0) | (mul_ln135_loc_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state10_pp0_stage6_iter0 = ((io_acc_block_signal_op193 == 1'b0) & (ap_predicate_op193_read_state10 == 1'b1));
end

always @ (*) begin
    ap_block_state11_pp0_stage7_iter0 = (((io_acc_block_signal_op202 == 1'b0) & (ap_predicate_op202_read_state11 == 1'b1)) | ((bytes_plane0_V_V_full_n == 1'b0) & (ap_predicate_op208_write_state11 == 1'b1)));
end

always @ (*) begin
    ap_block_state12_pp0_stage0_iter1 = (((io_acc_block_signal_op214 == 1'b0) & (ap_predicate_op214_read_state12 == 1'b1)) | ((or_ln639_2_reg_1411 == 1'd1) & (bytes_plane0_V_V_full_n == 1'b0)));
end

assign ap_block_state4_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state5_pp0_stage1_iter0 = ((io_acc_block_signal_op138 == 1'b0) & (ap_predicate_op138_read_state5 == 1'b1));
end

always @ (*) begin
    ap_block_state6_pp0_stage2_iter0 = ((io_acc_block_signal_op148 == 1'b0) & (ap_predicate_op148_read_state6 == 1'b1));
end

always @ (*) begin
    ap_block_state7_pp0_stage3_iter0 = ((io_acc_block_signal_op158 == 1'b0) & (ap_predicate_op158_read_state7 == 1'b1));
end

always @ (*) begin
    ap_block_state8_pp0_stage4_iter0 = (((io_acc_block_signal_op168 == 1'b0) & (ap_predicate_op168_read_state8 == 1'b1)) | ((bytes_plane0_V_V_full_n == 1'b0) & (ap_predicate_op175_write_state8 == 1'b1)));
end

always @ (*) begin
    ap_block_state9_pp0_stage5_iter0 = ((io_acc_block_signal_op181 == 1'b0) & (ap_predicate_op181_read_state9 == 1'b1));
end

always @ (*) begin
    ap_condition_1221 = ((or_ln627_reg_1399 == 1'd1) & (icmp_ln622_reg_1379 == 1'd1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1));
end

always @ (*) begin
    ap_condition_1224 = ((icmp_ln622_fu_1002_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (or_ln627_fu_1018_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_1229 = ((icmp_ln622_reg_1379 == 1'd1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_condition_1233 = ((icmp_ln622_reg_1379 == 1'd1) & (1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3));
end

always @ (*) begin
    ap_condition_1237 = ((icmp_ln622_reg_1379 == 1'd1) & (1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4));
end

always @ (*) begin
    ap_condition_1241 = ((icmp_ln622_reg_1379 == 1'd1) & (1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5));
end

always @ (*) begin
    ap_condition_1245 = ((icmp_ln622_reg_1379 == 1'd1) & (1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6));
end

always @ (*) begin
    ap_condition_548 = ((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_pix_val_V_0_8_i_i_reg_540 = 'bx;

assign ap_phi_reg_pp0_iter0_pix_val_V_1_8_i_i_reg_530 = 'bx;

assign ap_phi_reg_pp0_iter0_pix_val_V_2_8_i_i_reg_520 = 'bx;

assign ap_phi_reg_pp0_iter1_pix_val_V_0_9_i_i_reg_570 = 'bx;

assign ap_phi_reg_pp0_iter1_pix_val_V_1_9_i_i_reg_560 = 'bx;

assign ap_phi_reg_pp0_iter1_pix_val_V_2_9_i_i_reg_550 = 'bx;

always @ (*) begin
    ap_predicate_op138_read_state5 = ((or_ln627_reg_1399 == 1'd1) & (icmp_ln622_reg_1379 == 1'd1));
end

always @ (*) begin
    ap_predicate_op148_read_state6 = ((or_ln627_1_reg_1430 == 1'd1) & (icmp_ln622_reg_1379 == 1'd1));
end

always @ (*) begin
    ap_predicate_op158_read_state7 = ((or_ln627_2_reg_1449 == 1'd1) & (icmp_ln622_reg_1379 == 1'd1));
end

always @ (*) begin
    ap_predicate_op168_read_state8 = ((or_ln627_3_reg_1468 == 1'd1) & (icmp_ln622_reg_1379 == 1'd1));
end

always @ (*) begin
    ap_predicate_op175_write_state8 = ((or_ln639_reg_1403 == 1'd1) & (icmp_ln622_reg_1379 == 1'd1));
end

always @ (*) begin
    ap_predicate_op181_read_state9 = ((or_ln627_4_reg_1487 == 1'd1) & (icmp_ln622_reg_1379 == 1'd1));
end

always @ (*) begin
    ap_predicate_op193_read_state10 = ((or_ln627_5_reg_1506 == 1'd1) & (icmp_ln622_reg_1379 == 1'd1));
end

always @ (*) begin
    ap_predicate_op202_read_state11 = ((or_ln627_6_reg_1510 == 1'd1) & (icmp_ln622_reg_1379 == 1'd1));
end

always @ (*) begin
    ap_predicate_op208_write_state11 = ((or_ln639_1_reg_1407 == 1'd1) & (icmp_ln622_reg_1379 == 1'd1));
end

always @ (*) begin
    ap_predicate_op214_read_state12 = ((or_ln627_7_reg_1514 == 1'd1) & (icmp_ln622_reg_1379 == 1'd1));
end

assign icmp_ln260_fu_611_p2 = ((tmp_fu_601_p4 == 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln296_fu_617_p2 = ((VideoFormat == 8'd27) ? 1'b1 : 1'b0);

assign icmp_ln331_fu_639_p2 = ((tmp_1_fu_629_p4 == 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln367_fu_645_p2 = ((VideoFormat == 8'd12) ? 1'b1 : 1'b0);

assign icmp_ln403_fu_651_p2 = ((VideoFormat == 8'd28) ? 1'b1 : 1'b0);

assign icmp_ln437_fu_673_p2 = ((tmp_2_fu_663_p4 == 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln476_fu_695_p2 = ((tmp_3_fu_685_p4 == 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln522_fu_717_p2 = ((tmp_4_fu_707_p4 == 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln567_fu_739_p2 = ((tmp_5_fu_729_p4 == 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln604_fu_761_p2 = ((tmp_6_fu_751_p4 == 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln612_fu_817_p2 = ((remPix_fu_787_p1 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln618_fu_978_p2 = ((y_0_i_i_reg_303 == Height) ? 1'b1 : 1'b0);

assign icmp_ln622_fu_1002_p2 = (($signed(zext_ln622_fu_998_p1) < $signed(trunc_ln1_reg_1290)) ? 1'b1 : 1'b0);

assign icmp_ln627_1_fu_904_p2 = ((tmp_7_fu_894_p4 != 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln627_2_fu_910_p2 = ((remPix_2_fu_822_p3 > 4'd2) ? 1'b1 : 1'b0);

assign icmp_ln627_3_fu_926_p2 = ((tmp_8_fu_916_p4 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln627_4_fu_932_p2 = ((remPix_2_fu_822_p3 > 4'd4) ? 1'b1 : 1'b0);

assign icmp_ln627_5_fu_938_p2 = ((remPix_2_fu_822_p3 > 4'd5) ? 1'b1 : 1'b0);

assign icmp_ln627_6_fu_944_p2 = ((remPix_2_fu_822_p3 > 4'd6) ? 1'b1 : 1'b0);

assign icmp_ln627_7_fu_1013_p2 = (($signed(zext_ln622_fu_998_p1) < $signed(add_ln627_reg_1300)) ? 1'b1 : 1'b0);

assign icmp_ln627_fu_888_p2 = ((remPix_2_fu_822_p3 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln639_1_fu_966_p2 = ((tmp_9_fu_956_p4 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln639_2_fu_972_p2 = ((remainTrx_fu_874_p3 > 3'd2) ? 1'b1 : 1'b0);

assign icmp_ln639_fu_950_p2 = ((remainTrx_fu_874_p3 != 3'd0) ? 1'b1 : 1'b0);

assign io_acc_block_signal_op138 = (StrmMPix_V_val_2_V_empty_n & StrmMPix_V_val_1_V_empty_n & StrmMPix_V_val_0_V_empty_n);

assign io_acc_block_signal_op148 = (StrmMPix_V_val_2_V_empty_n & StrmMPix_V_val_1_V_empty_n & StrmMPix_V_val_0_V_empty_n);

assign io_acc_block_signal_op158 = (StrmMPix_V_val_2_V_empty_n & StrmMPix_V_val_1_V_empty_n & StrmMPix_V_val_0_V_empty_n);

assign io_acc_block_signal_op168 = (StrmMPix_V_val_2_V_empty_n & StrmMPix_V_val_1_V_empty_n & StrmMPix_V_val_0_V_empty_n);

assign io_acc_block_signal_op181 = (StrmMPix_V_val_2_V_empty_n & StrmMPix_V_val_1_V_empty_n & StrmMPix_V_val_0_V_empty_n);

assign io_acc_block_signal_op193 = (StrmMPix_V_val_2_V_empty_n & StrmMPix_V_val_1_V_empty_n & StrmMPix_V_val_0_V_empty_n);

assign io_acc_block_signal_op202 = (StrmMPix_V_val_2_V_empty_n & StrmMPix_V_val_1_V_empty_n & StrmMPix_V_val_0_V_empty_n);

assign io_acc_block_signal_op214 = (StrmMPix_V_val_2_V_empty_n & StrmMPix_V_val_1_V_empty_n & StrmMPix_V_val_0_V_empty_n);

assign mul_ln135_loc_out_din = mul_ln135_loc_dout;

assign mul_ln609_fu_1201_p0 = 30'd21846;

assign mul_ln609_fu_1201_p1 = mul_ln609_fu_1201_p10;

assign mul_ln609_fu_1201_p10 = add_ln609_fu_796_p2;

assign or_ln627_1_fu_1038_p2 = (icmp_ln627_7_reg_1388 | icmp_ln627_1_fu_904_p2);

assign or_ln627_2_fu_1042_p2 = (icmp_ln627_7_reg_1388 | icmp_ln627_2_fu_910_p2);

assign or_ln627_3_fu_1046_p2 = (icmp_ln627_7_reg_1388 | icmp_ln627_3_fu_926_p2);

assign or_ln627_4_fu_1050_p2 = (icmp_ln627_7_reg_1388 | icmp_ln627_4_fu_932_p2);

assign or_ln627_5_fu_1075_p2 = (icmp_ln627_7_reg_1388 | icmp_ln627_5_fu_938_p2);

assign or_ln627_6_fu_1079_p2 = (icmp_ln627_7_reg_1388 | icmp_ln627_6_fu_944_p2);

assign or_ln627_7_fu_1083_p2 = (icmp_ln627_7_reg_1388 | icmp_ln612_fu_817_p2);

assign or_ln627_fu_1018_p2 = (icmp_ln627_fu_888_p2 | icmp_ln627_7_fu_1013_p2);

assign or_ln639_1_fu_1028_p2 = (icmp_ln639_1_fu_966_p2 | icmp_ln627_7_fu_1013_p2);

assign or_ln639_2_fu_1033_p2 = (icmp_ln639_2_fu_972_p2 | icmp_ln627_7_fu_1013_p2);

assign or_ln639_fu_1023_p2 = (icmp_ln639_fu_950_p2 | icmp_ln627_7_fu_1013_p2);

assign remPix_2_fu_822_p3 = ((icmp_ln612_fu_817_p2[0:0] === 1'b1) ? 4'd8 : zext_ln611_fu_814_p1);

assign remPix_fu_787_p1 = WidthInPix[2:0];

assign remainTrx_fu_874_p3 = ((icmp_ln612_fu_817_p2[0:0] === 1'b1) ? 3'd3 : trunc_ln2_fu_864_p4);

assign shl_ln613_1_fu_841_p3 = {{remPix_fu_787_p1}, {3'd0}};

assign shl_ln_fu_830_p3 = {{remPix_fu_787_p1}, {5'd0}};

assign sub_ln613_fu_852_p2 = (zext_ln613_fu_837_p1 - zext_ln613_1_fu_848_p1);

assign tmp_1_fu_629_p4 = {{add_ln331_fu_623_p2[7:1]}};

assign tmp_2_fu_663_p4 = {{add_ln437_fu_657_p2[7:1]}};

assign tmp_3_fu_685_p4 = {{add_ln476_fu_679_p2[7:1]}};

assign tmp_4_fu_707_p4 = {{add_ln522_fu_701_p2[7:1]}};

assign tmp_5_fu_729_p4 = {{add_ln567_fu_723_p2[7:1]}};

assign tmp_6_fu_751_p4 = {{add_ln604_fu_745_p2[7:1]}};

assign tmp_7_fu_894_p4 = {{remPix_2_fu_822_p3[3:1]}};

assign tmp_8_fu_916_p4 = {{remPix_2_fu_822_p3[3:2]}};

assign tmp_9_fu_956_p4 = {{remainTrx_fu_874_p3[2:1]}};

assign tmp_V_1_fu_1087_p9 = {{{{{{{{ap_phi_reg_pp0_iter0_pix_val_V_0_7_i_i_reg_509}, {pix_val_V_2_6_i_i_reg_454}}, {pix_val_V_1_6_i_i_reg_465}}, {pix_val_V_0_6_i_i_reg_476}}, {pix_val_V_2_5_i_i_reg_421}}, {pix_val_V_1_5_i_i_reg_432}}, {pix_val_V_0_5_i_i_reg_443}}, {pix_val_V_2_4_i_i_reg_388}};

assign tmp_V_2_fu_1160_p9 = {{{{{{{{ap_phi_mux_pix_val_V_2_9_i_i_phi_fu_553_p4}, {ap_phi_mux_pix_val_V_1_9_i_i_phi_fu_563_p4}}, {ap_phi_mux_pix_val_V_0_9_i_i_phi_fu_573_p4}}, {ap_phi_reg_pp0_iter1_pix_val_V_2_8_i_i_reg_520}}, {ap_phi_reg_pp0_iter1_pix_val_V_1_8_i_i_reg_530}}, {ap_phi_reg_pp0_iter1_pix_val_V_0_8_i_i_reg_540}}, {pix_val_V_2_7_i_i_reg_487}}, {pix_val_V_1_7_i_i_reg_498}};

assign tmp_V_fu_1054_p9 = {{{{{{{{ap_phi_reg_pp0_iter0_pix_val_V_1_4_i_i_reg_399}, {ap_phi_reg_pp0_iter0_pix_val_V_0_4_i_i_reg_410}}, {pix_val_V_2_3_i_i_reg_355}}, {pix_val_V_1_3_i_i_reg_366}}, {pix_val_V_0_3_i_i_reg_377}}, {pix_val_V_2_2_i_i_reg_325}}, {pix_val_V_1_2_i_i_reg_335}}, {pix_val_V_0_2_i_i_reg_345}};

assign tmp_fu_601_p4 = {{add_ln260_fu_595_p2[7:1]}};

assign trunc_ln1_fu_805_p4 = {{mul_ln609_fu_1201_p2[28:16]}};

assign trunc_ln2_fu_864_p4 = {{add_ln613_fu_858_p2[8:6]}};

assign x_fu_1007_p2 = (ap_phi_mux_x_0_i_i_phi_fu_318_p4 + 12'd1);

assign y_fu_983_p2 = (y_0_i_i_reg_303 + 16'd1);

assign zext_ln608_fu_767_p1 = mul_ln135_loc_dout;

assign zext_ln611_fu_814_p1 = remPix_fu_787_p1;

assign zext_ln613_1_fu_848_p1 = shl_ln613_1_fu_841_p3;

assign zext_ln613_fu_837_p1 = shl_ln_fu_830_p3;

assign zext_ln622_fu_998_p1 = ap_phi_mux_x_0_i_i_phi_fu_318_p4;

endmodule //design_1_v_frmbuf_wr_0_0_MultiPixStream2Bytes
